### ISSUE TITLE
Исключение по значению цвета

### ISSUE THREAD

**Issue by xlam** [xlam/CyberBiology#9]
Требуется исправить расчет цвета бота. Иногда, при вызове событий мира (например "Сбой генома"), выбрасывается данное исключение:

```
Exception in thread "Thread-4" java.lang.IllegalArgumentException: Color parameter outside of expected range: Green
	at java.awt.Color.testColorValueRange(Color.java:310)
	at java.awt.Color.<init>(Color.java:395)
	at java.awt.Color.<init>(Color.java:369)
	at ru.cyberbiology.view.ViewEnergy.getBotColor(ViewEnergy.java:38)
	at ru.cyberbiology.prototype.view.View.paint(View.java:38)
	at ru.cyberbiology.MainWindow.paint(MainWindow.java:138)
	at ru.cyberbiology.World.paint(World.java:89)
	at ru.cyberbiology.World$Worker.run(World.java:179)
```
В первую очередь смотреть View.getBotColor().

**Comment by xlam** [comment]
Воспроизводимость данного бага очень редкая.
